apiVersion: v1
kind: Pod
metadata:
   name: enb
   annotations:
     cni.projectcalico.org/ipAddrs: "[\"192.186.4.253\"]"
spec:
   containers:
   - name: enb1
     image: captnko/enb
     securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
     # to keep running and ready
     command: [ "/bin/bash", "-c", "--" ]
     args: [ "while true; do sleep 30; done;" ]
     
