apiVersion: v1
kind: Pod
metadata:
   name: mongodb
   annotations:
     cni.projectcalico.org/ipAddrs: "[\"192.186.4.10\"]"
spec:
   containers:
   - name: mongodb
     image: captnko/mongodb-open5gs
     command: [ "/bin/bash", "-c", "--" ]
     args: [ "/etc/init.d/mongodb start;while true; do sleep 30; done;" ]
     
