apiVersion: v1
kind: Pod
metadata:
   name: oaisim
spec:
   containers:
   - name: enb
     image: captnko/enb
     securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
     # to keep running and ready
     command: [ "/bin/bash", "-c", "--" ]
     args: [ "while true; do sleep 30; done;" ]
   - name: ue
     image: captnko/ue
     securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
     # to keep running and ready
     command: [ "/bin/bash", "-c", "--" ]
     args: [ "while true; do sleep 30; done;" ]
     
