apiVersion: v1
kind: Pod
metadata:
   name: webui
#   annotations:
#     cni.projectcalico.org/ipAddrs: "[\"192.186.4.11\"]"
spec:
   containers:
   - name: webui
     image: captnko/webui-open5gs
     # to keep running and ready
     command: [ "/bin/bash", "-c", "--" ]
     args: [ "cd /open5gs/webui; npm run dev; while true; do sleep 30; done;" ]
     env:
        - name: DB_URI
          value: "mongodb://10.43.0.3:27017/open5gs" 
     
