apiVersion: v1
kind: Pod
metadata:
   name: epc
   annotations:
     cni.projectcalico.org/ipAddrs: "[\"192.186.4.2\"]"
spec:
   containers:
   - name: epc
     image: captnko/epc
     securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
     # to keep running and ready
     command: [ "/bin/bash", "-c", "--" ]
     args:
       - sysctl -w net.ipv6.conf.all.disable_ipv6=0;
         bash /open5gs/runEPC.sh;
         while true;
         do sleep 30;
         done;
   volumes:            
   - name: dev-net-tun
     hostPath:
       path: /dev/net/tun
     
