apiVersion: v1
kind: Service
metadata:
  name: epc-service
spec:
  selector:
    app: epc
# type: ClusterIP
  clusterIP: 10.96.0.2
  ports:
  - name: s1ap
    port: 36412
    protocol: SCTP
#    nodePort: 36412
#  - port: 2152
#    protocol: TCP 
#  externalIPs:
#    - 192.186.4.2       
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: epc
  labels:
    app: epc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: epc
  template:
    metadata:
      labels:
        app: epc
    spec:
      containers:
       - name: epc
         image: captnko/epc
         resources:
           requests:
             memory: "64Mi"
             cpu: "250m"
           limits:
             memory: "512Mi"
             cpu: "1000m"
         securityContext:
          privileged: true
          capabilities:
            add:
              - NET_ADMIN
         # to keep running and ready
         command: [ "/bin/bash", "-c", "--" ]
         args:
           - sysctl -w net.ipv6.conf.all.disable_ipv6=0;
             bash /open5gs/runEPC.sh;
             while true;
             do sleep 30;
             done;
      volumes:            
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
     
