apiVersion: v1
kind: Service
metadata:
  name: epc-service
spec:
  selector:
    app: epc
# type: ClusterIP
  clusterIP: 10.43.0.2
  ports:
  - name: s1ap
    port: 36412
    protocol: SCTP
  - name: gtpc
    port: 2123
    protocol: UDP
  - name: gtpu
    port: 2152
    protocol: UDP  
  - name: gx
    port: 3868
    protocol: TCP
#    nodePort: 36412
#  - port: 2152
#    protocol: TCP 
#  externalIPs:
#    - 192.186.4.2       
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet 
metadata:
  name: epc
spec:
  replicas: 1
  serviceName: "epc-service"
  selector:
    matchLabels:
      app: epc
  template:
    metadata:          
      labels:
        app: epc
    spec:
      containers:
        - name: epc
          image: captnko/epc
          securityContext:
            privileged: true
            #sysctls:
            #- name: net.ipv6.conf.all.disable_ipv6
            #  value: 0
            capabilities:
              add: ["NET_ADMIN"]
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - sysctl -w net.ipv6.conf.all.disable_ipv6=0;
              bash /open5gs/runEPC.sh;
              while true;
              do sleep 30;
              done;
          volumeMounts:
          - mountPath: /dev/net/tun
            name: dev-net-tun             
      volumes:            
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
