apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db
# type: ClusterIP
  clusterIP: 10.43.0.3
  ports:
#  - name: s1ap
#    port: 36412
#    protocol: SCTP
#    nodePort: 36412
  - port: 27017
    protocol: TCP 
#  externalIPs:
#    - 127.0.0.41       
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
       containers:
       - name: mongodb
         image: captnko/mongodb-open5gs
         command: [ "/bin/bash", "-c", "--" ]
         args: [ "/etc/init.d/mongodb start;while true; do sleep 30; done;" ]
     
