apiVersion: v1
kind: Pod
metadata:
   name: ue2
   annotations:
     cni.projectcalico.org/ipAddrs: "[\"192.186.4.252\"]"
spec:
   containers:
   - name: ue2
     image: captnko/ue2
     securityContext:
      privileged: true
      capabilities:
        add:
          - NET_ADMIN
     # to keep running and ready
     command: [ "/bin/bash", "-c", "--" ]
     args: [ "while true; do sleep 30; done;" ]
